services:
  website:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "2194:3000"
    environment:
      DATABASE_URL: "postgres://pin-tag:pin-tag@database:5432/pin-tag"
    depends_on:
      migrate:
        condition: service_completed_successfully
      database:
        condition: service_healthy


  migrate:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 'pnpm migrate deploy'
    environment:
      DATABASE_URL: "postgres://pin-tag:pin-tag@database:5432/pin-tag"
    depends_on:
      database:
        condition: service_healthy

  studio:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 'pnpm studio'
    environment:
      DATABASE_URL: "postgres://pin-tag:pin-tag@database:5432/pin-tag"
    depends_on:
      migrate:
        condition: service_completed_successfully
      database:
        condition: service_healthy
  
  database:
    image: "postgres:16"
    environment:
      POSTGRES_USER: "pin-tag"
      POSTGRES_PASSWORD: "pin-tag"
      POSTGRES_DB: "pin-tag"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', 'postgres://pin-tag:pin-tag@database:5432/pin-tag']
      interval: '10s'
      timeout: '5s'
      retries: 5

volumes:
  postgres_data:   